//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : BaseSample.cpp
//  @ Date : 22.05.2020
//  @ Author : 
//
//


#include "BaseSample.hxx"


Standard_Boolean BaseSample::IsProcessed()
{
  return Standard_True;
}

NCollection_Vector<Handle(AIS_InteractiveObject) > BaseSample::Get2dObject()
{
  return NCollection_Vector<Handle(AIS_InteractiveObject) >(NULL);
}

NCollection_Vector<Handle(AIS_InteractiveObject) > BaseSample::Get3dObject()
{
  return NCollection_Vector<Handle(AIS_InteractiveObject) >(NULL);
}

NCollection_Vector<NCollection_String> BaseSample::GetResult()
{
  return NCollection_Vector<NCollection_String>();
}

NCollection_Vector<NCollection_String> BaseSample::GetCode() 
{
  return NCollection_Vector<NCollection_String>();
}

