//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ComcreteSample.h
//  @ Date : 22.05.2020
//  @ Author : 
//
//


#if !defined(_COMCRETESAMPLE_H)
#define _COMCRETESAMPLE_H

#include "BaseSample.h"

class ComcreteSample : public BaseSample {
public:
	void Process();
};

#endif  //_COMCRETESAMPLE_H
