//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ComcreteSample.cpp
//  @ Date : 22.05.2020
//  @ Author : 
//
//


#include "ComcreteSample.hxx"

void ComcreteSample::Process() 
{

}



