// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _TOcafFunction_CylDriver_HeaderFile
#define _TOcafFunction_CylDriver_HeaderFile

#include <TFunction_Driver.hxx>
#include <TFunction_Logbook.hxx>

class TOcafFunction_CylDriver;
DEFINE_STANDARD_HANDLE(TOcafFunction_CylDriver, TFunction_Driver)


class TOcafFunction_CylDriver : public TFunction_Driver
{
public:
  DEFINE_STANDARD_RTTI_INLINE(TOcafFunction_CylDriver, TFunction_Driver)

  Standard_EXPORT static const Standard_GUID& GetID ();
  Standard_EXPORT TOcafFunction_CylDriver ();
  Standard_EXPORT virtual  void Validate (Handle (TFunction_Logbook)& log) const override;
  Standard_EXPORT virtual  Standard_Boolean MustExecute (const Handle (TFunction_Logbook)& log) const override;
  Standard_EXPORT virtual  Standard_Integer Execute (Handle (TFunction_Logbook)& log) const override;
};

#endif
