// File generated by CPPExt (Transient)
//
//                     Copyright (C) 1991,1995 by
//  
//                      MATRA DATAVISION, FRANCE
//  
// This software is furnished in accordance with the terms and conditions
// of the contract and with the inclusion of the above copyright notice.
// This software or any other copy thereof may not be provided or otherwise
// be made available to any other person. No title to an ownership of the
// software is hereby transferred.
//  
// At the termination of the contract, the software and all copies of this
// software must be deleted.
//
#ifndef _TOcaf_Application_HeaderFile
#define _TOcaf_Application_HeaderFile

#include <TDocStd_Application.hxx>
#include <TColStd_SequenceOfExtendedString.hxx>

class TOcaf_Application;
DEFINE_STANDARD_HANDLE(TOcaf_Application, TDocStd_Application)

class TOcaf_Application : public TDocStd_Application
{
public:
  DEFINE_STANDARD_RTTI_INLINE(TOcaf_Application, TDocStd_Application)

  Standard_EXPORT TOcaf_Application ();
};

#endif
